import { contextBridge, ipcRenderer } from 'electron';
import type { Api, AppEvent } from '../../packages/domain/types';
import type { IpcResult } from '../../packages/domain/errors';
const call = async <T>(method: string, ...args: unknown[]): Promise<T> => {
  const result = (await ipcRenderer.invoke('minedock:' + method, ...args)) as IpcResult<T>;
  if (result.ok) return result.value;
  throw Object.assign(new Error(result.error.message), {
    code: result.error.code,
    retryable: result.error.retryable,
  });
};
const api: Api = {
  exportPackage: (id, sensitive, confirmation) =>
    call('exportPackage', id, sensitive, confirmation),
  previewPackage: () => call('previewPackage'),
  importPackage: (input) => call('importPackage', input),
  testReachability: (id, input) => call('testReachability', id, input),
  mapPlan: (id, kind) => call('mapPlan', id, kind),
  mapApply: (id, input) => call('mapApply', id, input),
  mapStatus: (id) => call('mapStatus', id),
  openMap: (id, kind) => call('openMap', id, kind),
  configDocuments: (id) => call('configDocuments', id),
  editConfig: (id, input) => call('editConfig', id, input),
  configHistory: (id) => call('configHistory', id),
  restoreConfig: (id, version, confirmation) => call('restoreConfig', id, version, confirmation),
  configAudit: (id) => call('configAudit', id),
  performance: (id, hours) => call('performance', id, hours),
  searchHistoricalLogs: (id, input) => call('searchHistoricalLogs', id, input),
  runMacro: (id, input) => call('runMacro', id, input),
  saveMacro: (id, input) => call('saveMacro', id, input),
  latestMinecraft: (id) => call('latestMinecraft', id),
  migrationReview: (id, target) => call('migrationReview', id, target),
  applyMigration: (id, token, confirmation) => call('applyMigration', id, token, confirmation),
  cloneServer: (id, input) => call('cloneServer', id, input),
  incrementalSnapshots: (id) => call('incrementalSnapshots', id),
  createIncremental: (id) => call('createIncremental', id),
  previewPartial: (id, snapshot, scope) => call('previewPartial', id, snapshot, scope),
  restorePartial: (id, token, confirmation) => call('restorePartial', id, token, confirmation),
  backupSafety: () => call('backupSafety'),
  configureBackupSafety: (input) => call('configureBackupSafety', input),
  testBackupStorage: () => call('testBackupStorage'),
  playerDetails: (id, name) => call('playerDetails', id, name),
  playerNote: (id, name, note) => call('playerNote', id, name, note),
  playerSkin: (id, name) => call('playerSkin', id, name),
  setWhitelist: (id, enabled) => call('setWhitelist', id, enabled),
  health: (id) => call('health', id),
  healthSettings: () => call('healthSettings'),
  configureHealth: (input) => call('configureHealth', input),
  notices: () => call('notices'),
  readNotices: (id) => call('readNotices', id),
  crashReport: (id) => call('crashReport', id),
  revealCrash: (id) => call('revealCrash', id),
  packSearch: (id, kind, query) => call('packSearch', id, kind, query),
  packInventory: (id, kind, world) => call('packInventory', id, kind, world),
  packVersions: (id, kind, project) => call('packVersions', id, kind, project),
  packPlan: (id, input) => call('packPlan', id, input),
  packApply: (id, token) => call('packApply', id, token),
  packAction: (id, input) => call('packAction', id, input),
  packImport: (id, kind, world) => call('packImport', id, kind, world),
  modSearch: (id, input) => call('modSearch', id, input),
  modInventory: (id, force) => call('modInventory', id, force),
  modDetail: (id, project) => call('modDetail', id, project),
  modPlan: (id, input) => call('modPlan', id, input),
  modApply: (id, token) => call('modApply', id, token),
  modUpdates: (id) => call('modUpdates', id),
  modPin: (id, content, pinned) => call('modPin', id, content, pinned),
  modRemoval: (id, ids) => call('modRemoval', id, ids),
  modBulk: (id, input) => call('modBulk', id, input),
  modLibrary: () => call('modLibrary'),
  modFavorite: (id, project, favorite) => call('modFavorite', id, project, favorite),
  modCollection: (input) => call('modCollection', input),
  modDeleteCollection: (id) => call('modDeleteCollection', id),
  modHistory: (id) => call('modHistory', id),
  modReveal: (id, content) => call('modReveal', id, content),
  modManualToggle: (id, filename) => call('modManualToggle', id, filename),
  modIdentify: (id, filename) => call('modIdentify', id, filename),
  modMigration: (id, target) => call('modMigration', id, target),
  modMigrate: (id, target, confirmation) => call('modMigrate', id, target, confirmation),
  snapshot: () => call('snapshot'),
  diagnostic: () => call('diagnostic'),
  settings: (v) => call('settings', v),
  selectFolder: () => call('selectFolder'),
  openFolder: (id) => call('openFolder', id),
  versions: (engine) => call('versions', engine),
  builds: (engine, version) => call('builds', engine, version),
  installers: (engine) => call('installers', engine),
  create: (input) => call('create', input),
  previewServerImport: () => call('previewServerImport'),
  importServer: (input) => call('importServer', input),
  previewModpack: () => call('previewModpack'),
  createModpack: (selection, input) => call('createModpack', selection, input),
  worlds: (id) => call('worlds', id),
  worldAction: (id, input) => call('worldAction', id, input),
  previewWorldImport: (id, archive) => call('previewWorldImport', id, archive),
  importWorld: (id, input) => call('importWorld', id, input),
  exportWorld: (id, name) => call('exportWorld', id, name),
  retryInstallation: (id) => call('retryInstallation', id),
  cancelDownload: (id) => call('cancelDownload', id),
  operations: () => call('operations'),
  cancelOperation: (id) => call('cancelOperation', id),
  dismissOperation: (id) => call('dismissOperation', id),
  recoveryReview: (id) => call('recoveryReview', id),
  resolveOperation: (id, input) => call('resolveOperation', id, input),
  start: (id) => call('start', id),
  stop: (id) => call('stop', id),
  restart: (id) => call('restart', id),
  remove: (id, confirmation) => call('remove', id, confirmation),
  logs: (id) => call('logs', id),
  command: (id, command) => call('command', id, command),
  players: (id) => call('players', id),
  playerReport: (id) => call('playerReport', id),
  moderatePlayer: (id, input) => call('moderatePlayer', id, input),
  properties: (id) => call('properties', id),
  saveProperties: (id, props) => call('saveProperties', id, props),
  configureServer: (id, options) => call('configureServer', id, options),
  files: (id, path) => call('files', id, path),
  readFile: (id, path) => call('readFile', id, path),
  writeFile: (id, path, content) => call('writeFile', id, path, content),
  mkdir: (id, path) => call('mkdir', id, path),
  deleteFile: (id, path, confirm) => call('deleteFile', id, path, confirm),
  uploadFile: (id, path) => call('uploadFile', id, path),
  exportFile: (id, path) => call('exportFile', id, path),
  fileAction: (id, input) => call('fileAction', id, input),
  compressArchive: (id, path) => call('compressArchive', id, path),
  extractArchive: (id, input) => call('extractArchive', id, input),
  backup: (id) => call('backup', id),
  verifyBackup: (id) => call('verifyBackup', id),
  restore: (id, confirm) => call('restore', id, confirm),
  exportBackup: (id) => call('exportBackup', id),
  deleteBackup: (id, confirm) => call('deleteBackup', id, confirm),
  retentionPolicy: (id) => call('retentionPolicy', id),
  configureRetention: (id, input) => call('configureRetention', id, input),
  previewRetention: (id) => call('previewRetention', id),
  purgeRetention: (id, input) => call('purgeRetention', id, input),
  updateStatus: () => call('updateStatus'),
  configureUpdates: (automaticChecks) => call('configureUpdates', automaticChecks),
  checkUpdates: () => call('checkUpdates'),
  downloadUpdate: () => call('downloadUpdate'),
  installUpdate: (confirmation) => call('installUpdate', confirmation),
  schedules: (input) => call('schedules', input),
  deleteSchedule: (id) => call('deleteSchedule', id),
  toggleSchedule: (id, enabled) => call('toggleSchedule', id, enabled),
  schedulePreview: (input) => call('schedulePreview', input),
  metrics: (id, hours) => call('metrics', id, hours),
  storageOverview: (id) => call('storageOverview', id),
  scanStorage: (id) => call('scanStorage', id),
  revealStorageFile: (id, input) => call('revealStorageFile', id, input),
  runtimes: () => call('runtimes'),
  installRuntime: (major) => call('installRuntime', major),
  runtimeEntries: () => call('runtimeEntries'),
  runtimeHealth: (id) => call('runtimeHealth', id),
  repairRuntime: (input) => call('repairRuntime', input),
  deleteRuntime: (input) => call('deleteRuntime', input),
  search: (id, query, provider) => call('search', id, query, provider),
  installContent: (id, project, provider, version) =>
    call('installContent', id, project, provider, version),
  marketplaceSettings: () => call('marketplaceSettings'),
  contentIcon: (url) => call('contentIcon', url),
  crossplayStatus: (id) => call('crossplayStatus', id),
  crossplayVersions: (id) => call('crossplayVersions', id),
  configureCrossplay: (id, input) => call('configureCrossplay', id, input),
  clearIconCache: () => call('clearIconCache'),
  configureMarketplace: (input) => call('configureMarketplace', input),
  content: (id) => call('content', id),
  toggleContent: (id, content) => call('toggleContent', id, content),
  contentVersions: (id, project, provider) => call('contentVersions', id, project, provider),
  contentVersion: (provider, version) => call('contentVersion', provider, version),
  contentUpdates: (id) => call('contentUpdates', id),
  contentHistory: (id, content) => call('contentHistory', id, content),
  manualContent: (id) => call('manualContent', id),
  changeContentVersion: (id, content, version, confirmation) =>
    call('changeContentVersion', id, content, version, confirmation),
  uninstallContent: (id, content, confirmation) =>
    call('uninstallContent', id, content, confirmation),
  rollbackContent: (id, content, history, confirmation) =>
    call('rollbackContent', id, content, history, confirmation),
  onEvent: (listener) => {
    const receive = (_event: Electron.IpcRendererEvent, event: AppEvent): void => listener(event);
    ipcRenderer.on('minedock:event', receive);
    return () => ipcRenderer.removeListener('minedock:event', receive);
  },
};
contextBridge.exposeInMainWorld('minedock', api);
